# TUGAS 2

**DIKRITISASI**

Diskritisasi adalah proses menempatkan nilai ke dalam wadah sehingga ada sejumlah kemungkinan status. Wadah itu sendiri diperlakukan sebagai nilai yang diurutkan dan diskrit.

Deskritisasi atau binning digunakan untuk mengubah atribut numerik menjadi atribut kategorikal. Perubahan tersebut dilakukan dengan mengkategorikan atribut numerik menjadi beberapa tingkatan atribut kategorikal.

**Metoda Binning:**

Diskritisasi Sederhana 

Partisi lebar yang sama (jarak):
 
- Membagi range kedalam N interval dengan ukuran yang sama: grid seragam
- Jika A dan B masing-masing adalah nilai terendah dan tertinggi dari atribut, lebar interval akan menjadi : W = (B –A)/N
- Kebanyakan langsung, tetapi outlier mendominasi presentasi
- Data Outlier dan menyimpang tidak ditangani dengan baik.


Partisi kedalaman sama (frekuensi):
- Membagi range kedalam N interval, masing-masing memuat jumlah sampel yang hampir sama
- Penskalaan data yang baik
- Penanganan atribut yang bersifat kategori bisa rumit.

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset_url="https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
data=pd.read_csv(dataset_url)
pd.options.mode.chained_assignment = None

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
data[['sepal_length']]

     sepal_length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
..            ...
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

In [5]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')

In [6]:
data['sepal_length']=est.fit_transform(data[['sepal_length']])

In [7]:
data['sepal_length']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    1.0
Name: sepal_length, Length: 150, dtype: float64

In [8]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['sepal_width']=est.fit_transform(data[['sepal_width']])

In [9]:
data['sepal_width']

0      2.0
1      1.0
2      2.0
3      1.0
4      2.0
      ...
145    1.0
146    0.0
147    1.0
148    2.0
149    1.0
Name: sepal_width, Length: 150, dtype: float64

In [10]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['petal_length']=est.fit_transform(data[['petal_length']])

In [11]:
data['petal_length']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: petal_length, Length: 150, dtype: float64

In [12]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['petal_width']=est.fit_transform(data[['petal_width']])

In [13]:
data['petal_width']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    3.0
146    3.0
147    3.0
148    3.0
149    2.0
Name: petal_width, Length: 150, dtype: float64

**ENTROPY**

Entropi adalah nilai informasi yang menyatakan ukuran ketidakpastian(impurity) dari attribut dari suatu kumpulan obyek data dalam satuan bit

membuat sampel untuk dianalisis

In [14]:
import pandas as pd
import numpy as np

In [15]:
dataset_url="https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
data=pd.read_csv(dataset_url)

In [16]:
sampel = data[["sepal_length"]]
sampel.describe()

       sepal_length
count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000

membuat category random untuk semua data

In [17]:
np.random.seed(0)
sampel["category"] = np.where(np.random.choice(2, sampel.shape[0]) < 1, "A", "B")
sampel

     sepal_length category
0             5.1        A
1             4.9        B
2             4.7        B
3             4.6        A
4             5.0        B
..            ...      ...
145           6.7        A
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

membuat fungsi getOverCategory yang digunakan untuk menghitung data keseluruhan yang nantinya digunakan untuk menghitung entropy

In [18]:
def getOverCategory(col):
  group = sampel.loc[:, :].groupby("category").count()
  a = group.loc["A", col]
  b = group.loc["B", col]
  return (a, b, a+b)

fungsi splitter digunakan untuk membuat split antara value yang telah ditentukan lalu mengembalikan data yang telah dipisahkan

In [19]:
def splitter(value:float, col:str)->tuple:
  # get data less and greater from value
  less = sampel[sampel[col] <= value]
  greater = sampel[sampel[col] > value]

  # calculate into category for each data
  less_group = less.loc[:, :].groupby("category").count()
  greater_group = greater.loc[:, :].groupby("category").count()

  # get value based on category
  less_category_A = less_group.loc["A", col] 
  less_category_B = less_group.loc["B", col] 
  greater_category_A = greater_group.loc["A", col] 
  greater_category_B = greater_group.loc["B", col] 

  return (
      [less_category_A, less_category_B, less_category_A + less_category_B],
      [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
  )

Membuat fungsi entropy untuk mencari nilai entropy

Rumus Mencari Entropy : 
$$
Entropy (D_{1}) = - \sum_{i=1}^{m} pi \log_{2} pi
$$

In [20]:
def entropy(d):
  r1 = (d[0] / d[2]) * np.log2(d[0] / d[2]) 
  r2 = (d[1] / d[2]) * np.log2(d[1] / d[2]) 
  return np.sum([r1, r2]) * -1

Membuat fungsi info

In [21]:
def info(d):
  r1 = (d[0][2] / sampel.shape[0]) * entropy(d[0])
  r2 = (d[1][2] / sampel.shape[0]) * entropy(d[1])
  return r1 + r2

Membuat fungsi gain untuk menghitung selisih antara entropy awal dengan yang baru.

Rumus Mencari Gain : 
$$
Gain(E_{new}) = (E_{initial}) - (E_{new})
$$

In [22]:
def gain(Einitial, Enew):
  return Einitial - Enew

Membuat Dinitial

In [23]:
D = getOverCategory("sepal_length")
entropy_d = entropy(D)
print(D)
print(entropy_d)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk mencari hasil dan informasi yang terbaik

Tes Pertama : Split 1:4.4

In [24]:
split1  = splitter(4.4, "sepal_length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.003488151753460178

Tes Kedua : Split 2:5.5

In [25]:
split2  = splitter(5.5, "sepal_length")
info_split2 = info(split2)
gain(entropy_d, info_split2)

0.012302155146638905

Tes Ketiga : Split 3:7.0

In [26]:
split3  = splitter(7.0, "sepal_length")
info_split3 = info(split3)
gain(entropy_d, info_split3)

0.0005490214732508658

Dari seluruh hasil percobaan tes split yang telah dilakukan, maka diperoleh hasil split terbaik adalah split 3 yang mwemberikan keuntungan informasi sebesar 0.0005490214732508658, karena hasil tes split 3 memiliki nilai split yang terendah.

In [27]:
np.random.seed(0)
data["category"] = np.where(np.random.choice(2,data.shape[0]) < 1,"A","B")
data

     sepal_length  sepal_width  petal_length  petal_width    species category
0             5.1          3.5           1.4          0.2     setosa        A
1             4.9          3.0           1.4          0.2     setosa        B
2             4.7          3.2           1.3          0.2     setosa        B
3             4.6          3.1           1.5          0.2     setosa        A
4             5.0          3.6           1.4          0.2     setosa        B
..            ...          ...           ...          ...        ...      ...
145           6.7          3.0           5.2          2.3  virginica        A
146           6.3          2.5           5.0          1.9  virginica        B
147           6.5          3.0           5.2          2.0  virginica        B
148           6.2          3.4           5.4          2.3  virginica        B
149           5.9          3.0           5.1          1.8  virginica        B

[150 rows x 6 columns]